# Example 2

# This will catch all error and print a message
try:
    print(x)
except:
    print("There is an error")  # There is an error
